services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow:
    build: .
    user: "0:0"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      MLFLOW_TRACKING_URI: http://mlflow:5001
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: standalone

  mlflow:
    build: .
    ports:
      - "5001:5001"
    environment:
      - BACKEND_STORE_URI=sqlite:////opt/mlflow/mlflow.db
    volumes:
      - .:/opt/mlflow
    command: uv run mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri sqlite:////opt/mlflow/mlflow.db --default-artifact-root /opt/mlflow/mlruns

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - MODEL_NAME=PAL_Passenger_Segmenter
      - MODEL_VERSION=v1.0.0
      - MODEL_ARTIFACT_PATH=/app/models/pal_passenger_segmenter_v1.0.0.joblib
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - mlflow

volumes:
  postgres-db-volume:
